[package]
name = "shiplog-btree"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "B-Tree implementation for shiplog."
readme = "README.md"

[dependencies]
anyhow.workspace = true
