[package]
name = "shiplog-watcher"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "File system watcher for real-time shiplog sync."
readme = "README.md"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
notify = "8.0.0"

[dev-dependencies]
tempfile.workspace = true
