[package]
name = "shiplog-watch"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "File system watching for changes in shiplog."
readme = "README.md"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
notify = { version = "8.0.0", default-features = false, features = ["macos_kqueue"] }
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
