[package]
name = "shiplog-testkit"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
shiplog-ids = { path = "../shiplog-ids", version = "0.1.1" }
shiplog-schema = { path = "../shiplog-schema", version = "0.1.1" }

[dev-dependencies]
shiplog-redact = { path = "../shiplog-redact", version = "0.1.1" }
serde.workspace = true

