[package]
name = "shiplog-testkit"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Shared test fixtures and utilities for shiplog crates"
readme = "README.md"
documentation = "https://docs.rs/shiplog-testkit"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
chrono.workspace = true
shiplog-ids = { path = "../shiplog-ids", version = "0.2.0" }
shiplog-schema = { path = "../shiplog-schema", version = "0.2.0" }

[dev-dependencies]
shiplog-redact = { path = "../shiplog-redact", version = "0.2.0" }
serde.workspace = true

