[package]
name = "shiplog-filter"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Filtering logic for shiplog events based on criteria."
readme = "README.md"
documentation = "https://docs.rs/shiplog-filter"
repository.workspace = true
homepage.workspace = true
keywords = ["filter", "events", "query", "criteria"]
categories = ["data-structures", "development-tools"]

[dependencies]
serde.workspace = true
shiplog-schema = { path = "../shiplog-schema", version = "0.2.1" }
shiplog-ids = { path = "../shiplog-ids", version = "0.2.1" }
chrono.workspace = true
itertools.workspace = true

[dev-dependencies]
proptest.workspace = true
