[package]
name = "shiplog-redact"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
sha2.workspace = true
hex.workspace = true
shiplog-schema = { path = "../shiplog-schema", version = "0.1.1" }
shiplog-ports = { path = "../shiplog-ports", version = "0.1.1" }

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true
chrono.workspace = true
shiplog-ids = { path = "../shiplog-ids", version = "0.1.1" }

