[package]
name = "shiplog-leakybucket"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Leaky bucket implementation for shiplog."
readme = "README.md"
documentation = "https://docs.rs/shiplog-leakybucket"
repository.workspace = true
homepage.workspace = true
keywords = ["bucket", "leaky-bucket", "rate-limiting"]
categories = ["caching", "development-tools"]

[dependencies]
anyhow.workspace = true
chrono.workspace = true
