[package]
name = "shiplog-scheduler"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Task scheduling utilities for shiplog."
readme = "README.md"
documentation = "https://docs.rs/shiplog-scheduler"
repository.workspace = true
homepage.workspace = true
keywords = ["scheduler", "tasks", "cron"]
categories = ["development-tools"]

[dependencies]
serde.workspace = true
anyhow.workspace = true
chrono.workspace = true

[dev-dependencies]
proptest.workspace = true
