[package]
name = "shiplog-env"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Environment variable utilities for shiplog."
readme = "README.md"

[dependencies]
