[package]
name = "shiplog-url"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "URL parsing and utilities for shiplog."
readme = "README.md"

[dependencies]
url.workspace = true
