[package]
name = "shiplog-windowing"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Windowing utilities for stream processing in shiplog."
readme = "README.md"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
