[package]
name = "shiplog-coverage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
shiplog-schema = { path = "../shiplog-schema" }

[dev-dependencies]
anyhow.workspace = true
