[package]
name = "shiplog-render-md"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
itertools.workspace = true
shiplog-schema = { path = "../shiplog-schema", version = "0.1.1" }
shiplog-ports = { path = "../shiplog-ports", version = "0.1.1" }

[dev-dependencies]
insta.workspace = true
shiplog-ids = { path = "../shiplog-ids", version = "0.1.1" }

