[package]
name = "shiplog-diff"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Diff algorithms for comparing shiplog events and packets."
readme = "README.md"
documentation = "https://docs.rs/shiplog-diff"
repository.workspace = true
homepage.workspace = true
keywords = ["diff", "compare", "events", "packet"]
categories = ["data-structures", "development-tools"]

[dependencies]
serde.workspace = true
shiplog-schema = { path = "../shiplog-schema", version = "0.2.1" }
shiplog-ids = { path = "../shiplog-ids", version = "0.2.1" }
chrono.workspace = true

[dev-dependencies]
proptest.workspace = true
